[theme]
primaryColor = "#007CC3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5FA"
textColor = "#1E1E1E"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
